export const REQUEST_POKEMONS = 'REQUEST_POKEMONS'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'

export const POKEMON_LOAD = 'POKEMON_LOAD'
export const POKEMON_LOAD_SUCCESS = 'POKEMON_LOAD_SUCCESS'
export const POKEMON_LOAD_ERROR = 'POKEMON_LOAD_ERROR'

export const POKEMON_DETAIL = 'POKEMON_DETAIL'
export const POKEMON_DETAIL_SUCCESS = 'POKEMON_DETAIL_SUCCESS'
export const POKEMON_DETAIL_ERROR = 'POKEMON_DETAIL_ERROR'
