export const REQUEST = 'REQUEST'
export const RECEIVE = 'RECEIVE'

export const POKEMON_ADD = 'POKEMON_ADD'
export const POKEMON_REMOVE = 'POKEMON_REMOVE'

export const POKEMON_LOAD = 'POKEMON_LOAD'
export const POKEMON_LOAD_REPLACE = 'POKEMON_LOAD_REPLACE'
export const POKEMON_LOAD_SUCCESS = 'POKEMON_LOAD_SUCCESS'
export const POKEMON_LOAD_ERROR = 'POKEMON_LOAD_ERROR'

export const POKEMON_DETAIL = 'POKEMON_DETAIL'
export const POKEMON_DETAIL_SUCCESS = 'POKEMON_DETAIL_SUCCESS'
export const POKEMON_DETAIL_ERROR = 'POKEMON_DETAIL_ERROR'
